// Generates llms.txt — a Markdown summary placed at the site root so that
// AI crawlers and answer engines get a clean, structured view of the brand.

export function generateLlms(audit) {
    const { company } = audit;
    const lines = [];

    lines.push(`# ${company.name}`);
    lines.push('');
    if (company.description) {
        lines.push(`> ${company.description.replace(/\n+/g, ' ')}`);
        lines.push('');
    }
    lines.push(`- Website: ${company.url}`);
    if (company.industry) lines.push(`- Industry: ${company.industry}`);
    if (company.email) lines.push(`- Contact: ${company.email}`);
    if (company.phone) lines.push(`- Phone: ${company.phone}`);
    if (company.address) {
        const parts = [company.address.street, company.address.zip, company.address.city, company.address.country]
            .filter(Boolean)
            .join(', ');
        if (parts) lines.push(`- Location: ${parts}`);
    }
    if (company.founder) {
        lines.push(`- Founder: ${company.founder.name}${company.founder.title ? ` (${company.founder.title})` : ''}`);
    }
    if (company.languages.length) lines.push(`- Languages: ${company.languages.join(', ')}`);
    lines.push('');

    if (audit.services.length) {
        lines.push('## Services');
        lines.push('');
        for (const service of audit.services) {
            lines.push(service.description ? `- **${service.name}** — ${service.description}` : `- **${service.name}**`);
        }
        lines.push('');
    }

    if (audit.pages.length) {
        lines.push('## Key pages');
        lines.push('');
        for (const page of audit.pages) {
            const label = page.title || page.url;
            lines.push(page.description ? `- [${label}](${page.url}): ${page.description}` : `- [${label}](${page.url})`);
        }
        lines.push('');
    }

    if (audit.faq.length) {
        lines.push('## FAQ');
        lines.push('');
        for (const item of audit.faq) {
            lines.push(`### ${item.question}`);
            lines.push('');
            lines.push(item.answer.replace(/\n+/g, ' '));
            lines.push('');
        }
    }

    if (audit.keywords.length) {
        lines.push('## Topics');
        lines.push('');
        lines.push(audit.keywords.join(', '));
        lines.push('');
    }

    if (company.social.length) {
        lines.push('## Profiles');
        lines.push('');
        for (const url of company.social) lines.push(`- ${url}`);
        lines.push('');
    }

    lines.push('---');
    lines.push(`Generated by Searchora — ${audit.generatedAt.slice(0, 10)}`);
    lines.push('');

    return lines.join('\n');
}
