'use client';

import { useState } from 'react';
import Link from '@/components/ui/LocaleLink';
import { ArrowRight, Check, X, HelpCircle } from 'lucide-react';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import AnimatedSection from '@/components/ui/AnimatedSection';
import { Section, SectionLabel, SectionTitle } from '@/components/ui/Section';
import { useI18n } from '@/lib/i18n';

export default function PricingPage() {
    const [openFaq, setOpenFaq] = useState(null);
    const [annual, setAnnual] = useState(false);
    const { t } = useI18n();

    const plans = [
        {
            name: t('pricing.starter'),
            price: '490',
            period: t('common.month'),
            description: t('pricing.starterDesc'),
            features: [
                { text: '1 website tracked', included: true },
                { text: 'Monthly AI visibility audit', included: true },
                { text: '25 prompts monitored', included: true },
                { text: 'Basic visibility score', included: true },
                { text: 'Email reports', included: true },
                { text: 'Content recommendations', included: true },
                { text: 'Competitor tracking', included: false },
                { text: 'Priority support', included: false },
                { text: 'Custom integrations', included: false },
                { text: 'Dedicated manager', included: false },
            ],
            cta: t('pricing.startFree'),
            variant: 'secondary',
            popular: false,
        },
        {
            name: t('pricing.growth'),
            price: '1,290',
            period: t('common.month'),
            description: t('pricing.growthDesc'),
            features: [
                { text: '5 websites tracked', included: true },
                { text: 'Weekly AI visibility audits', included: true },
                { text: '100 prompts monitored', included: true },
                { text: 'Advanced visibility scoring', included: true },
                { text: 'Real-time dashboards', included: true },
                { text: 'AI content recommendations', included: true },
                { text: '3 competitors tracked', included: true },
                { text: 'Priority support', included: true },
                { text: 'Custom integrations', included: false },
                { text: 'Dedicated manager', included: false },
            ],
            cta: t('pricing.startTrial'),
            variant: 'primary',
            popular: true,
        },
        {
            name: t('pricing.enterprise'),
            price: t('pricing.custom'),
            period: '',
            description: t('pricing.enterpriseDesc'),
            features: [
                { text: 'Unlimited websites', included: true },
                { text: 'Daily AI visibility audits', included: true },
                { text: 'Unlimited prompts monitored', included: true },
                { text: 'Enterprise visibility suite', included: true },
                { text: 'Real-time dashboards + API', included: true },
                { text: 'Full AI content engine', included: true },
                { text: 'Unlimited competitors', included: true },
                { text: '24/7 priority support', included: true },
                { text: 'Custom integrations', included: true },
                { text: 'Dedicated account manager', included: true },
            ],
            cta: t('pricing.contactSales'),
            variant: 'dark',
            popular: false,
        },
    ];

    const faqs = [
        {
            q: 'What is AI visibility?',
            a: 'AI visibility measures how often and how prominently your brand appears in answers generated by AI tools like ChatGPT, Gemini, Copilot, and Perplexity.',
        },
        {
            q: 'How long does it take to see results?',
            a: 'Most clients see measurable improvements within 4-8 weeks after implementing our recommendations.',
        },
        {
            q: 'Can I cancel anytime?',
            a: 'Yes. All plans are monthly and can be cancelled at any time. Enterprise plans have custom terms.',
        },
        {
            q: 'Do you offer a free trial?',
            a: 'Yes. We offer a free AI visibility audit for all new clients, plus a 14-day free trial of the Growth plan.',
        },
        {
            q: 'What AI platforms do you monitor?',
            a: 'We monitor ChatGPT, Gemini, Copilot, Perplexity, Claude, and several other AI assistants.',
        },
    ];

    return (
        <>
            {/* Hero */}
            <section className="bg-white pt-12 pb-16 section-padding">
                <div className="container-wide">
                    <AnimatedSection>
                        <div className="text-center max-w-3xl mx-auto">
                            <SectionLabel className="mb-4">{t('pricing.label')}</SectionLabel>
                            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-text-primary leading-[1.1] tracking-tight mb-6">
                                {t('pricing.title')}
                            </h1>
                            <p className="text-lg text-text-secondary leading-relaxed max-w-2xl mx-auto mb-8">
                                {t('pricing.subtitle')}
                            </p>

                            <div className="inline-flex items-center gap-3 bg-surface-secondary rounded-xl p-1">
                                <button
                                    onClick={() => setAnnual(false)}
                                    className={`px-4 py-2 text-sm font-medium rounded-lg transition-all cursor-pointer ${!annual ? 'bg-white text-text-primary shadow-sm' : 'text-text-secondary'
                                        }`}
                                >
                                    {t('pricing.monthly')}
                                </button>
                                <button
                                    onClick={() => setAnnual(true)}
                                    className={`px-4 py-2 text-sm font-medium rounded-lg transition-all cursor-pointer ${annual ? 'bg-white text-text-primary shadow-sm' : 'text-text-secondary'
                                        }`}
                                >
                                    {t('pricing.annual')} <span className="text-brand text-xs">{t('pricing.annualDiscount')}</span>
                                </button>
                            </div>
                        </div>
                    </AnimatedSection>
                </div>
            </section>

            {/* Plans */}
            <Section background="gray">
                <div className="grid md:grid-cols-3 gap-6 lg:gap-8">
                    {plans.map((plan, i) => (
                        <AnimatedSection key={plan.name} delay={i * 100}>
                            <Card
                                hover={false}
                                padding="p-0"
                                className={`h-full flex flex-col overflow-hidden ${plan.popular ? 'border-brand ring-1 ring-brand/20 relative' : ''
                                    }`}
                            >
                                {plan.popular && (
                                    <div className="bg-brand text-white text-[10px] font-semibold uppercase tracking-widest text-center py-2">
                                        {t('pricing.mostPopular')}
                                    </div>
                                )}
                                <div className="p-8 flex-1 flex flex-col">
                                    <div className="mb-6">
                                        <h3 className="text-lg font-semibold text-text-primary mb-1">{plan.name}</h3>
                                        <p className="text-sm text-text-secondary mb-4">{plan.description}</p>
                                        <div className="flex items-baseline gap-1">
                                            {plan.price === t('pricing.custom') ? (
                                                <span className="text-4xl font-bold text-text-primary">{plan.price}</span>
                                            ) : (
                                                <>
                                                    <span className="text-sm text-text-muted">€</span>
                                                    <span className="text-4xl font-bold text-text-primary">
                                                        {annual ? Math.round(parseInt(plan.price.replace(',', '')) * 0.8).toLocaleString() : plan.price}
                                                    </span>
                                                    <span className="text-sm text-text-muted">{plan.period}</span>
                                                </>
                                            )}
                                        </div>
                                    </div>

                                    <ul className="space-y-3 mb-8 flex-1">
                                        {plan.features.map((feature) => (
                                            <li key={feature.text} className="flex items-start gap-2.5">
                                                {feature.included ? (
                                                    <Check className="w-4 h-4 text-brand mt-0.5 shrink-0" />
                                                ) : (
                                                    <X className="w-4 h-4 text-gray-300 mt-0.5 shrink-0" />
                                                )}
                                                <span className={`text-sm ${feature.included ? 'text-text-secondary' : 'text-text-muted'}`}>
                                                    {feature.text}
                                                </span>
                                            </li>
                                        ))}
                                    </ul>

                                    <Link href={plan.popular ? '/signup' : plan.variant === 'dark' ? '/contact' : '/signup'} className="block">
                                        <Button variant={plan.variant} size="lg" className="w-full" icon={ArrowRight} iconPosition="right">
                                            {plan.cta}
                                        </Button>
                                    </Link>
                                </div>
                            </Card>
                        </AnimatedSection>
                    ))}
                </div>
            </Section>

            {/* FAQ */}
            <Section>
                <AnimatedSection>
                    <div className="text-center mb-12">
                        <SectionLabel className="mb-4">FAQ</SectionLabel>
                        <SectionTitle className="mb-4">{t('pricing.faqTitle')}</SectionTitle>
                    </div>
                </AnimatedSection>

                <div className="max-w-2xl mx-auto space-y-3">
                    {faqs.map((faq, i) => (
                        <AnimatedSection key={faq.q} delay={i * 50}>
                            <div className="border border-border rounded-xl overflow-hidden">
                                <button
                                    onClick={() => setOpenFaq(openFaq === i ? null : i)}
                                    className="w-full flex items-center justify-between px-6 py-4 text-left cursor-pointer hover:bg-surface-secondary transition-colors"
                                >
                                    <span className="text-sm font-medium text-text-primary pr-4">{faq.q}</span>
                                    <HelpCircle className={`w-4 h-4 shrink-0 transition-colors ${openFaq === i ? 'text-brand' : 'text-text-muted'}`} />
                                </button>
                                <div className={`transition-all duration-300 overflow-hidden ${openFaq === i ? 'max-h-40' : 'max-h-0'}`}>
                                    <p className="px-6 pb-4 text-sm text-text-secondary leading-relaxed">{faq.a}</p>
                                </div>
                            </div>
                        </AnimatedSection>
                    ))}
                </div>
            </Section>

            {/* CTA */}
            <Section background="dark">
                <AnimatedSection>
                    <div className="text-center max-w-2xl mx-auto">
                        <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4 tracking-tight">
                            {t('pricing.startFree')}
                        </h2>
                        <p className="text-lg text-gray-400 mb-8">
                            {t('pricing.subtitle')}
                        </p>
                        <Link href="/contact">
                            <Button size="lg" icon={ArrowRight} iconPosition="right">
                                {t('nav.requestAudit')}
                            </Button>
                        </Link>
                    </div>
                </AnimatedSection>
            </Section>
        </>
    );
}
